### ISSUE TITLE
Probleme de date - Creation / Update de projet

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/node-api#22]
Les problèmes :
1. Les datas sont en doubles voir en triple dans la db
2. Certains projets n'ont pas de dates valides ex: "Un vélo pour Sam" ou "Un mac pour Maeva"

Les id des projets qui posent problème : 6 - 8 - 9 - 12 - 13 - 14 - 15

**Comment by MRWS** [comment]
@VictorLuc4 Je peux close ça ?

**Comment by VictorLuc4** [comment]
Oui
