### ISSUE TITLE
[API] Affichage du Contrat

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/node-api#45]
## General 
Permet de récupérer les infos du contrat (signature, + information sur les 2 protagonistes) afin de l'afficher et pouvoir le télécharger depuis l'application. 

## Infos complémentaires
La feature à été re-négociée , plus besoin de générer un PDF, l'endpoint doit renvoyer simplement les informations sur les deux utilisateurs ainsi que les signatures.

## Description technique
- [ ] créer l'endpoint
> GET /projects/contract
> Params : {project_id}

## Pré-requis supplémentaire pour être valide
- [ ] La documentation doit être updatées
- [ ] Le code doit avoir été validé par @VictorLuc4 ou @MRWS

**Comment by MRWS** [comment]
Done on endpoint : `GET /offers/:id`
