### ISSUE TITLE
Envoi infos contrat

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/node-api#46]
## Issue
Il faut pouvoir envoyer les infos d'un contrat coté investisseur.

Il faudrait donc un endpoint lorsque l'investisseur signe le contrat ou j'envoie les infos + l'image.

## Discussion
Faut-il que j'envoie l'image de la signature directement dans la requête ? Ou faut il que je fasse une deuxième requête ?

**Comment by MRWS** [comment]
Done on `POST /offers`
