### ISSUE TITLE
[API] En tant qu'utilisateur, je peux consulter la liste des demandes de prêts

### ISSUE THREAD

**Issue by MRWS** [HETIC-W3-G12/node-api#7]
## Description générale

Renvoi la liste globale des demandes de prêt en cours.

## Description technique
- [ ] Projects list  
> GET /loans
> Response : 
 ```javascript 
 {
  uid: string,
  user_uid: string,
  title: string,
  price: string,
  time_laps: string,
  description: string,
  interests: string
}
 ```

## Pré-requis

- [x] Les routes doivent être définies et validées par @VictorLuc4 
- [ ] Les payloads doit être définies et validées par @VictorLuc4
- [ ] Le code doit avoir été validé par @samchery ou @MRWS 
- [ ] La Seed doit avoir été remplie

**Comment by MRWS** [comment]
## Routes

#### GET /loans
```
{
  
}
```

**Comment by VictorLuc4** [comment]
Je verrai plutôt 

```javascript
{
  uid: string,
  user_uid: string,
  ...
}
```

Pour plus de clarté. :)

**Comment by MRWS** [comment]
Ok j'update mon comment du dessus

**Comment by VictorLuc4** [comment]
Egalement : 

```javascript
{
  ...
  price: integer,
  time_laps: integer,
  interests: float,
  ...
}
```

**Comment by VictorLuc4** [comment]
On a également besoin d'un `final_price` qui est en fait le `price + (interests * price)`, on pourrait le calculer directement sur l'app mais ce ne serait pas safe je pense... Qu'en pensez vous ?

**Comment by MRWS** [comment]
Ok pour calculer les interets dans l'api. On peut stocker la valeur calculée + le pourcentage (avec une valeur par défaut dans un premier temps) directement en db.

**Comment by MRWS** [comment]
Il faudrait également penser à gérer l'état de pret.

Par exemple une colonne `state` avec un enum `open`, `filled` et `canceled` ?

**Comment by samchery** [comment]
**Intérêt**.
Je pensais on s'en préoccupais pas pour le moment ? Que y'avait qu'un seul taux & qu'on voyait ça ensuite ?

**Satus**. 
Yes faut ajouter. Par contre, y'a d'autres status : 
- avant la validation par les admin de la demande
- en attente de financement
- financé/en cours de remboursement
- terminé (complete)
- annulé (canceled)

je sais pas quoi mettre au status pour que ce soit clair.

Dans la DB. uid n'existe pas, c'est id, et avec user_uid, c'est des integer... 

price & time_laps pour moi c'est aussi des chiffres. Dans le sens où nombre de mois et nombre en euro ... non ?

**Comment by VictorLuc4** [comment]
Oui bonne idée j'avais zappé qu'on ne faisait pas ça. 

Oui `price` et `time` sont des Integers, je l'ai mis dans un commentaire juste au dessus.

Je comprend pas quand tu dis que dans la DB uid n'existe pas. Tu m'expliques ça lundi ? (ça sera plus simple).

**Comment by samchery** [comment]
Terminé 👍
